
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* AddBucketResponseMessage
*/
public class AddBucketResponseMessage {
	//If the operation was successful, the status will be in the 200-299 range.
	@JsonProperty("Status")
	public int Status;

	@JsonProperty("Message")
	public String Message = "";

	@JsonProperty("NewBucketID")
	public String NewBucketID = "";

	@JsonProperty("NewBucketKey")
	public String NewBucketKey = "";


	public AddBucketResponseMessage(){ }

	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	static public AddBucketResponseMessage fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,AddBucketResponseMessage.class);
	}

	public CometAPIResponseMessage GetEmbeddedCometAPIResponseMessage(){
		var ret = new CometAPIResponseMessage();
		ret.Status = this.Status;
		ret.Message = this.Message;
		return ret;
	}
	public void SetEmbeddedCometAPIResponseMessage(CometAPIResponseMessage other){
		this.Status = other.Status;
		this.Message = other.Message;
	}

	public NewBucketDetail GetEmbeddedNewBucketDetail(){
		var ret = new NewBucketDetail();
		ret.NewBucketID = this.NewBucketID;
		ret.NewBucketKey = this.NewBucketKey;
		return ret;
	}
	public void SetEmbeddedNewBucketDetail(NewBucketDetail other){
		this.NewBucketID = other.NewBucketID;
		this.NewBucketKey = other.NewBucketKey;
	}

}
