
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* AdminWebAuthnRegistration
*/
public class AdminWebAuthnRegistration {
	@JsonProperty("Description")
	public String Description = "";

	//Unix timestamp, in seconds.
	@JsonProperty("RegisterTime")
	public long RegisterTime;

	@JsonProperty("Type")
	public int Type;

	@JsonProperty("IsLegacyU2F")
	public boolean IsLegacyU2F;

	@JsonProperty("ID")
	public byte[] ID;

	@JsonProperty("Credential")
	public WebAuthnCredential Credential;


	public AdminWebAuthnRegistration(){ }

	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	static public AdminWebAuthnRegistration fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,AdminWebAuthnRegistration.class);
	}

}
