
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* B2StorageExtraInfo
*/
public class B2StorageExtraInfo {
	@JsonProperty("TotalTransactionsInTimeInterval")
	public HashMap<Long, B2TransactionTotals> TotalTransactionsInTimeInterval;


	public B2StorageExtraInfo(){ }

	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	static public B2StorageExtraInfo fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,B2StorageExtraInfo.class);
	}

}
