
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* DiskDrive
*/
public class DiskDrive {
	@JsonProperty("ID")
	public String ID = "";

	@JsonProperty("DeviceName")
	public String DeviceName = "";

	@JsonProperty("Caption")
	public String Caption = "";

	@JsonProperty("Model")
	public String Model = "";

	@JsonProperty("SerialNumber")
	public String SerialNumber = "";

	@JsonProperty("Size")
	public long Size;

	@JsonProperty("Partitions")
	public ArrayList<Partition> Partitions;

	@JsonProperty("Flags")
	public long Flags;

	@JsonProperty("Cylinders")
	public long Cylinders;

	@JsonProperty("Heads")
	public long Heads;

	@JsonProperty("Sectors")
	public long Sectors;

	@JsonProperty("SectorSize")
	public long SectorSize;


	public DiskDrive(){ }

	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	static public DiskDrive fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,DiskDrive.class);
	}

}
