
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* EDBFileInfo
*/
public class EDBFileInfo {
	@JsonProperty("Name")
	public String Name = "";

	@JsonProperty("Guid")
	public String GUID = "";

	@JsonProperty("ServerName")
	public String ServerName = "";

	@JsonProperty("CircularLoggingEnabled")
	public boolean CircularLoggingEnabled;


	public EDBFileInfo(){ }

	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	static public EDBFileInfo fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,EDBFileInfo.class);
	}

}
