
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* ExternalLDAPAuthenticationSourceServer
*/
public class ExternalLDAPAuthenticationSourceServer {
	@JsonProperty("Hostname")
	public String Hostname = "";

	@JsonProperty("Port")
	public int Port;

	//One of the LDAPSECURITYMETHOD_ constants (e.g. "plain" / "ldaps" / "starttls")
	@JsonProperty("SecurityMethod")
	public String SecurityMethod = "";

	@JsonProperty("AcceptInvalidSSL")
	public boolean AcceptInvalidSSL;


	public ExternalLDAPAuthenticationSourceServer(){ }

	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	static public ExternalLDAPAuthenticationSourceServer fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,ExternalLDAPAuthenticationSourceServer.class);
	}

}
