
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* ExtraFileExclusion
*/
public class ExtraFileExclusion {
	//The glob or regular expression to exclude from backup jobs
	@JsonProperty("Exclude")
	public String Exclude = "";

	//Choose whether the 'Exclude' parameter will be treated as a regular expression (true) or a glob (false)
	@JsonProperty("Regex")
	public boolean Regex;

	//Either OS_ANY or one of the OS_ONLY constants
	@JsonProperty("RestrictOS")
	public int RestrictOS;


	public ExtraFileExclusion(){ }

	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	static public ExtraFileExclusion fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,ExtraFileExclusion.class);
	}

}
