
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* GroupPolicy
*/
public class GroupPolicy {
	@JsonProperty("Description")
	public String Description = "";

	@JsonProperty("OrganizationID")
	public String OrganizationID = "";

	@JsonProperty("Policy")
	public UserPolicy Policy;

	//DefaultUserPolicy marks that this UserPolicy should be applied to all new users. The Comet Server will ensure that
	//only one policy can be set as default.
	@JsonProperty("DefaultUserPolicy")
	public boolean DefaultUserPolicy;

	//Unix timestamp in seconds. May be zero for Policies created prior to Comet 23.3.3.
	@JsonProperty("CreatedDate")
	public long CreatedDate;

	//Unix timestamp in seconds. May be zero for Policies created prior to Comet 23.3.3.
	@JsonProperty("ModifiedDate")
	public long ModifiedDate;


	public GroupPolicy(){ }

	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	static public GroupPolicy fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,GroupPolicy.class);
	}

}
