
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* HTTPConnectorOptions
*/
public class HTTPConnectorOptions {
	@JsonProperty("ListenAddress")
	public String ListenAddress__DONOTUSEDIRECTLY = "";

	@JsonProperty("SSLCertPath")
	public String SSLCertPath = "";

	@JsonProperty("SSLIntermediate")
	public String SSLIntermediate = "";

	@JsonProperty("SSLCertKey")
	public String SSLCertKey = "";

	@JsonProperty("AutoSSLDomains")
	public String AutoSSLDomains = "";

	@JsonProperty("SSLPfxPath")
	public String SSLPfxPath = "";

	@JsonProperty("SSLPfxPassword")
	public String SSLPfxPassword = "";


	public HTTPConnectorOptions(){ }

	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	static public HTTPConnectorOptions fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,HTTPConnectorOptions.class);
	}

}
