
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* OrganizationLoginURLResponse
*/
public class OrganizationLoginURLResponse {
	@JsonProperty("LoginURL")
	public String LoginURL = "";


	public OrganizationLoginURLResponse(){ }

	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	static public OrganizationLoginURLResponse fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,OrganizationLoginURLResponse.class);
	}

}
