
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* ServerConfigOptionsBrandingFragment
*/
public class ServerConfigOptionsBrandingFragment {
	@JsonProperty("Branding")
	public BrandingOptions Branding;


	public ServerConfigOptionsBrandingFragment(){ }

	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	static public ServerConfigOptionsBrandingFragment fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,ServerConfigOptionsBrandingFragment.class);
	}

}
