
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* SourceBasicInfo SourceBasicInfo is the minimal amount of information one device knows about another device's Protected
* Items, in order to safely perform retention passes on their behalf.
*/
public class SourceBasicInfo {
	@JsonProperty("Description")
	public String Description = "";

	@JsonProperty("O365AccountCount")
	public long O365AccountCount;

	//Bytes
	@JsonProperty("Size")
	public long Size;

	@JsonProperty("OverrideDestinationRetention")
	public HashMap<String, RetentionPolicy> OverrideDestinationRetention;


	public SourceBasicInfo(){ }

	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	static public SourceBasicInfo fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,SourceBasicInfo.class);
	}

}
