
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* SourceStatistics
*/
public class SourceStatistics {
	@JsonProperty("LastBackupJob")
	public BackupJobDetail LastBackupJob;

	@JsonProperty("LastSuccessfulBackupJob")
	public BackupJobDetail LastSuccessfulBackupJob;


	public SourceStatistics(){ }

	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	static public SourceStatistics fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,SourceStatistics.class);
	}

}
