
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* StatResult
*/
public class StatResult {
	@JsonProperty("Buckets")
	public long Buckets;

	@JsonProperty("Users")
	public long Users;

	@JsonProperty("Devices")
	public long Devices;

	@JsonProperty("Boosters")
	public long Boosters;

	@JsonProperty("NetworkDevices")
	public long NetworkDevices;


	public StatResult(){ }

	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	static public StatResult fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,StatResult.class);
	}

}
