
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* StorageVaultProviderPolicy
*/
public class StorageVaultProviderPolicy {
	@JsonProperty("ShouldRestrictProviderList")
	public boolean ShouldRestrictProviderList;

	@JsonProperty("AllowedProvidersWhenRestricted")
	public ArrayList<Long> AllowedProvidersWhenRestricted;


	public StorageVaultProviderPolicy(){ }

	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	static public StorageVaultProviderPolicy fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,StorageVaultProviderPolicy.class);
	}

}
