
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* StorjDestinationLocation
*/
public class StorjDestinationLocation {
	@JsonProperty("SatelliteAddress")
	public String SatelliteAddress = "";

	@JsonProperty("APIKey")
	public String APIKey = "";

	@JsonProperty("Passphrase")
	public String Passphrase = "";

	@JsonProperty("StorjBucket")
	public String StorjBucket = "";

	@JsonProperty("StorjBucketPrefix")
	public String StorjBucketPrefix = "";


	public StorjDestinationLocation(){ }

	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	static public StorjDestinationLocation fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,StorjDestinationLocation.class);
	}

}
