
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* SwiftDestinationLocation
*/
public class SwiftDestinationLocation {
	//Username or UserID or Application Credential name or Application Credential ID, or blank for token authentication
	@JsonProperty("Username")
	public String Username = "";

	//User Password, or Application Credential Key, or token if the Username field is blank
	@JsonProperty("APIKey")
	public String APIKey = "";

	@JsonProperty("Region")
	public String Region = "";

	//Mandatory
	@JsonProperty("AuthURL")
	public String AuthURL = "";

	@JsonProperty("Domain")
	public String Domain = "";

	//Tenant name (v2) or Project name (v3)
	@JsonProperty("Tenant")
	public String Tenant = "";

	//Project domain name (v3)
	@JsonProperty("TenantDomain")
	public String TenantDomain = "";

	@JsonProperty("TenantID")
	public String TenantID = "";

	@JsonProperty("TrustID")
	public String TrustID = "";


	// deprecated since Comet version 17.8.0
	@JsonProperty("AuthToken")
	public String AuthToken = "";

	@JsonProperty("Prefix")
	public String Prefix = "";

	@JsonProperty("Container")
	public String Container = "";

	@JsonProperty("DefaultContainerPolicy")
	public String DefaultContainerPolicy = "";


	public SwiftDestinationLocation(){ }

	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	static public SwiftDestinationLocation fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,SwiftDestinationLocation.class);
	}

}
