
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* VMwareConnection
*/
public class VMwareConnection {
	//One of the VMWARE_CONNECTION_ constants
	@JsonProperty("ConnectionType")
	public String ConnectionType = "";

	@JsonProperty("SSH")
	public SSHConnection SSH;

	@JsonProperty("VSphere")
	public VSphereConnection VSphere;


	public VMwareConnection(){ }

	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	static public VMwareConnection fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,VMwareConnection.class);
	}

}
