
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* VSSWriterInfo
*/
public class VSSWriterInfo {
	@JsonProperty("DisplayName")
	public String DisplayName = "";

	@JsonProperty("Components")
	public ArrayList<VSSComponent> Components;


	public VSSWriterInfo(){ }

	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	static public VSSWriterInfo fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,VSSWriterInfo.class);
	}

}
