
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* WebAuthnPublicKeyCredentialRequestOptions
*/
public class WebAuthnPublicKeyCredentialRequestOptions {
	@JsonProperty("challenge")
	public byte[] Challenge;

	@JsonProperty("timeout")
	public int Timeout;

	@JsonProperty("rpId")
	public String RelyingPartyID = "";

	@JsonProperty("allowCredentials")
	public ArrayList<WebAuthnCredentialDescriptor> AllowedCredentials;

	@JsonProperty("userVerification")
	public String UserVerification = "";

	@JsonProperty("extensions")
	public HashMap<String, Object> Extensions;


	public WebAuthnPublicKeyCredentialRequestOptions(){ }

	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	static public WebAuthnPublicKeyCredentialRequestOptions fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,WebAuthnPublicKeyCredentialRequestOptions.class);
	}

}
