
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* WebDavDestinationLocation
* @since Version : 23.6.9
*/
public class WebDavDestinationLocation {
	//The URL of the WebDAV server, including http/https and any custom port
	@JsonProperty("DavServer")
	public String DavServer = "";

	//The username for logging in to the WebDAV server
	@JsonProperty("UserName")
	public String UserName = "";

	//The password for logging in to the WebDAV server
	@JsonProperty("AccessKey")
	public String AccessKey = "";

	//The target directory path within the WebDAV server
	@JsonProperty("Path")
	public String Path = "";


	public WebDavDestinationLocation(){ }

	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	static public WebDavDestinationLocation fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,WebDavDestinationLocation.class);
	}

}
