
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* WebhookOption WebhookOption defines the configuration of a webhook target. The Comet Server will send a live HTTP POST
* event to the webhook URL when certain events happen.
*/
public class WebhookOption {
	//The target URL to POST the event data to
	@JsonProperty("URL")
	public String URL = "";

	//CustomHeaders allows specifying custom headers which are added to the outgoing POST request
	//from Comet Server. Custom headers are specified as (header name, header value) pairs. If a
	//custom header conflicts with a header required by HTTP or the Comet tracing ID header
	//(`x-Comet-Tracing-Id`), it will be ignored.
	@JsonProperty("CustomHeaders")
	public HashMap<String, String> CustomHeaders;

	//One of the STREAM_LEVEL_ constants. This controls how much data is sent in the webhook event.
	@JsonProperty("Level")
	public String Level = "";

	//Configure a subset of allowed event types (see SEVT_ constants). If the array is empty, all events will be sent
	@JsonProperty("WhiteListedEventTypes")
	public ArrayList<Integer> WhiteListedEventTypes;


	public WebhookOption(){ }

	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	static public WebhookOption fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,WebhookOption.class);
	}

}
