
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* WinSMBAuth
*/
public class WinSMBAuth {
	//The UNC path for the Windows network share (SMB).
	@JsonProperty("SharePath")
	public String SharePath = "";

	//The username to log in to the Windows network share (SMB).
	@JsonProperty("Username")
	public String Username = "";

	//The password might be hashed. To set this in cleartext, set PasswordFormat to 0 (PASSWORD_FORMAT_PLAINTEXT).
	@JsonProperty("Password")
	public String Password = "";

	//The hash algorithm that is used for the Password field. It is one of the PASSWORD_FORMAT_ constants.
	@JsonProperty("PasswordFormat")
	public long PasswordFormat;


	public WinSMBAuth(){ }

	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	static public WinSMBAuth fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,WinSMBAuth.class);
	}

}
