
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* AdminAccountPropertiesResponse
*/
public class AdminAccountPropertiesResponse {
	@JsonProperty("OrganizationID")
	public String OrganizationID = "";

	@JsonProperty("Permissions")
	public AdminUserPermissions Permissions;

	@JsonProperty("Security")
	public AdminSecurityOptions Security;


	public AdminAccountPropertiesResponse(){ }

	/**
	* @return JSON representation of the AdminAccountPropertiesResponse
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a AdminAccountPropertiesResponse
	* @return The deserialized AdminAccountPropertiesResponse
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public AdminAccountPropertiesResponse fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,AdminAccountPropertiesResponse.class);
	}

}
