
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* AdminUserPermissions
*/
public class AdminUserPermissions {
	@JsonProperty("PreventEditServerSettings")
	public boolean PreventEditServerSettings;

	@JsonProperty("PreventServerShutdown")
	public boolean PreventServerShutdown;

	@JsonProperty("PreventChangePassword")
	public boolean PreventChangePassword;

	@JsonProperty("AllowEditBranding")
	public boolean AllowEditBranding;

	@JsonProperty("AllowEditEmailOptions")
	public boolean AllowEditEmailOptions;

	@JsonProperty("AllowEditRemoteStorage")
	public boolean AllowEditRemoteStorage;

	@JsonProperty("AllowEditWebhooks")
	public boolean AllowEditWebhooks;

	@JsonProperty("AllowEditExternalAuthSources")
	public boolean AllowEditExternalAuthSources;

	@JsonProperty("DenyConstellationRole")
	public boolean DenyConstellationRole;

	@JsonProperty("DenyViewServerHistory")
	public boolean DenyViewServerHistory;

	@JsonProperty("DenyViewServerInfo")
	public boolean DenyViewServerInfo;

	@JsonProperty("PreventDeleteStorageVault")
	public boolean PreventDeleteStorageVault;

	@JsonProperty("PreventRequestStorageVault")
	public boolean PreventRequestStorageVault;

	@JsonProperty("PreventAddCustomStorageVault")
	public boolean PreventAddCustomStorageVault;

	@JsonProperty("HideCloudStorageBranding")
	public boolean HideCloudStorageBranding;

	@JsonProperty("ShouldRestrictProviderList")
	public boolean ShouldRestrictProviderList;

	@JsonProperty("AllowedProvidersWhenRestricted")
	public ArrayList<Long> AllowedProvidersWhenRestricted;

	@JsonProperty("AllowedUserPolicies")
	public ArrayList<String> AllowedUserPolicies;

	@JsonProperty("DenySoftwareBuildRole")
	public boolean DenySoftwareBuildRole;


	public AdminUserPermissions(){ }

	/**
	* @return JSON representation of the AdminUserPermissions
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a AdminUserPermissions
	* @return The deserialized AdminUserPermissions
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public AdminUserPermissions fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,AdminUserPermissions.class);
	}

}
