
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* AdminU2FRegistration
// deprecated since Comet version 21.12.0
*/
public class AdminU2FRegistration {
	@JsonProperty("Description")
	public String Description = "";

	//Unix timestamp, in seconds.
	@JsonProperty("RegisterTime")
	public long RegisterTime;

	@JsonProperty("Registration")
	public byte[] Registration;


	public AdminU2FRegistration(){ }

	/**
	* @return JSON representation of the AdminU2FRegistration
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a AdminU2FRegistration
	* @return The deserialized AdminU2FRegistration
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public AdminU2FRegistration fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,AdminU2FRegistration.class);
	}

}
