
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* AdminSecurityOptions
*/
public class AdminSecurityOptions {
	//One of the PASSWORD_FORMAT_ constants
	@JsonProperty("PasswordFormat")
	public int PasswordFormat;

	@JsonProperty("Password")
	public String Password = "";

	@JsonProperty("AllowPasswordLogin")
	public boolean AllowPasswordLogin;

	@JsonProperty("AllowPasswordAndTOTPLogin")
	public boolean AllowPasswordAndTOTPLogin;


	// deprecated since Comet version 21.12.0
	@JsonProperty("AllowPasswordAndU2FLogin")
	public boolean AllowPasswordAndU2FLogin;

	@JsonProperty("AllowPasswordAndWebAuthnLogin")
	public boolean AllowPasswordAndWebAuthnLogin;


	// deprecated since Comet version 21.12.0
	@JsonProperty("U2FRegistrations")
	public ArrayList<AdminU2FRegistration> U2FRegistrations;

	@JsonProperty("WebAuthnRegistrations")
	public ArrayList<AdminWebAuthnRegistration> WebAuthnRegistrations;

	//One of the ENCRYPTIONMETHOD_ constants
	@JsonProperty("TOTPKeyEncryptionFormat")
	public int TOTPKeyEncryptionFormat;

	@JsonProperty("TOTPKey")
	public String TOTPKey = "";

	//A regular expression in Go regex syntax, for which IP addresses are allowed to authenticate as this admin account
	@JsonProperty("IPWhitelist")
	public String IPWhitelist = "";


	public AdminSecurityOptions(){ }

	/**
	* @return JSON representation of the AdminSecurityOptions
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a AdminSecurityOptions
	* @return The deserialized AdminSecurityOptions
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public AdminSecurityOptions fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,AdminSecurityOptions.class);
	}

}
