
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* AdminOptions
*/
public class AdminOptions {
	@JsonProperty("Policy")
	public PolicyOptions Policy;


	public AdminOptions(){ }

	/**
	* @return JSON representation of the AdminOptions
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a AdminOptions
	* @return The deserialized AdminOptions
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public AdminOptions fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,AdminOptions.class);
	}

}
