
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* AuthenticationRoleOptions
*/
public class AuthenticationRoleOptions {
	@JsonProperty("RoleEnabled")
	public boolean RoleEnabled;

	//One of the INTEGRITYCHECK_ constants
	@JsonProperty("DatabaseCheckLevel")
	public int DatabaseCheckLevel;

	@JsonProperty("GenerateMissedBackupEvents")
	public boolean GenerateMissedBackupEvents;

	//Unix timestamp in seconds, before which no Missed jobs are created
	@JsonProperty("NoMissedBackupEventsBefore")
	public long NoMissedBackupEventsBefore;

	@JsonProperty("GenerateScheduledEmails")
	public boolean GenerateScheduledEmails;

	@JsonProperty("PruneLogsAfterDays")
	public int PruneLogsAfterDays;

	@JsonProperty("RemoteStorage")
	public ArrayList<RemoteStorageOption> RemoteStorage;

	@JsonProperty("ReplicateTo")
	public ArrayList<ReplicaServer> ReplicateTo;

	@JsonProperty("GlobalOverrides")
	public GlobalOverrideOptions GlobalOverrides;


	public AuthenticationRoleOptions(){ }

	/**
	* @return JSON representation of the AuthenticationRoleOptions
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a AuthenticationRoleOptions
	* @return The deserialized AuthenticationRoleOptions
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public AuthenticationRoleOptions fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,AuthenticationRoleOptions.class);
	}

}
