
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* B2StorageExtraInfo
*/
public class B2StorageExtraInfo {
	@JsonProperty("TotalTransactionsInTimeInterval")
	public HashMap<Long, B2TransactionTotals> TotalTransactionsInTimeInterval;


	public B2StorageExtraInfo(){ }

	/**
	* @return JSON representation of the B2StorageExtraInfo
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a B2StorageExtraInfo
	* @return The deserialized B2StorageExtraInfo
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public B2StorageExtraInfo fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,B2StorageExtraInfo.class);
	}

}
