
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* B2TransactionTotals
*/
public class B2TransactionTotals {
	@JsonProperty("ClassA")
	public long ClassA;

	@JsonProperty("ClassB")
	public long ClassB;

	@JsonProperty("ClassC")
	public long ClassC;


	public B2TransactionTotals(){ }

	/**
	* @return JSON representation of the B2TransactionTotals
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a B2TransactionTotals
	* @return The deserialized B2TransactionTotals
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public B2TransactionTotals fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,B2TransactionTotals.class);
	}

}
