
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* B2VirtualStorageRoleSettings
*/
public class B2VirtualStorageRoleSettings {
	@JsonProperty("MasterBucket")
	public String MasterBucket = "";

	@JsonProperty("KeyID")
	public String KeyID = "";

	@JsonProperty("AppKey")
	public String AppKey = "";

	@JsonProperty("HideDeletedFiles")
	public boolean HideDeletedFiles;


	public B2VirtualStorageRoleSettings(){ }

	/**
	* @return JSON representation of the B2VirtualStorageRoleSettings
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a B2VirtualStorageRoleSettings
	* @return The deserialized B2VirtualStorageRoleSettings
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public B2VirtualStorageRoleSettings fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,B2VirtualStorageRoleSettings.class);
	}

}
