
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* BackupJobProgress
*/
public class BackupJobProgress {
	//This field will always increase monotonically, exactly once, for every change to the BackupJobProgress for a given
	//backup job.
	@JsonProperty("Counter")
	public long Counter;

	//Unix timestamp in seconds
	@JsonProperty("SentTime")
	public long SentTime;

	//Unix timestamp in seconds. The typo is preserved for backwards-compatibility reasons.
	@JsonProperty("RecievedTime")
	public long RecievedTime;

	@JsonProperty("BytesDone")
	public long BytesDone;

	@JsonProperty("ItemsDone")
	public long ItemsDone;


	public BackupJobProgress(){ }

	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	static public BackupJobProgress fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,BackupJobProgress.class);
	}

}
