
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* BlockInfo
*/
public class BlockInfo {
	@JsonProperty("DeviceID")
	public String DeviceID = "";

	@JsonProperty("DiskNodeName")
	public String DiskNodeName = "";


	public BlockInfo(){ }

	/**
	* @return JSON representation of the BlockInfo
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a BlockInfo
	* @return The deserialized BlockInfo
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public BlockInfo fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,BlockInfo.class);
	}

}
