
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* BrowseVMwareDatastoresResponse BrowseVMwareHostsResponse contains a list of VMware Datastores for a specific VMware
* Datacenter, when remotely browsing a VMware vSphere connection.
*/
public class BrowseVMwareDatastoresResponse {
	//If the operation was successful, the status will be in the 200-299 range.
	@JsonProperty("Status")
	public int Status;

	@JsonProperty("Message")
	public String Message = "";

	@JsonProperty("Datastores")
	public ArrayList<VMwareDatastoreInfo> Datastores;


	public BrowseVMwareDatastoresResponse(){ }

	/**
	* @return JSON representation of the BrowseVMwareDatastoresResponse
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a BrowseVMwareDatastoresResponse
	* @return The deserialized BrowseVMwareDatastoresResponse
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public BrowseVMwareDatastoresResponse fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,BrowseVMwareDatastoresResponse.class);
	}

	/**
	* @return Returns a copy of the embedded CometAPIResponseMessage
	*/
	public CometAPIResponseMessage GetEmbeddedCometAPIResponseMessage(){
		var ret = new CometAPIResponseMessage();
		ret.Status = this.Status;
		ret.Message = this.Message;
		return ret;
	}
	public void SetEmbeddedCometAPIResponseMessage(CometAPIResponseMessage other){
		this.Status = other.Status;
		this.Message = other.Message;
	}

}
