
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* CometDestinationLocation
*/
public class CometDestinationLocation {
	//The URL for the target Comet Server Storage Role, including http/https and trailing slash
	@JsonProperty("CometServer")
	public String CometServer = "";

	@JsonProperty("CometBucket")
	public String CometBucket = "";

	@JsonProperty("CometBucketKey")
	public String CometBucketKey = "";


	public CometDestinationLocation(){ }

	/**
	* @return JSON representation of the CometDestinationLocation
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a CometDestinationLocation
	* @return The deserialized CometDestinationLocation
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public CometDestinationLocation fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,CometDestinationLocation.class);
	}

}
