
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* ConstellationCheckReport
*/
public class ConstellationCheckReport {
	//Unix timestamp in seconds
	@JsonProperty("CheckStarted")
	public long CheckStarted;

	//Unix timestamp in seconds
	@JsonProperty("CheckCompleted")
	public long CheckCompleted;

	@JsonProperty("Usage")
	public HashMap<String, BucketUsageInfo> Usage;


	public ConstellationCheckReport(){ }

	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	static public ConstellationCheckReport fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,ConstellationCheckReport.class);
	}

}
