
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* ConstellationStatusAPIResponse
*/
public class ConstellationStatusAPIResponse {
	@JsonProperty("DeletionEnabled")
	public boolean DeletionEnabled;

	@JsonProperty("Targets")
	public ArrayList<String> Targets;

	@JsonProperty("TargetNames")
	public ArrayList<String> TargetNames;

	@JsonProperty("Stats")
	public ConstellationStats Stats;


	public ConstellationStatusAPIResponse(){ }

	/**
	* @return JSON representation of the ConstellationStatusAPIResponse
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a ConstellationStatusAPIResponse
	* @return The deserialized ConstellationStatusAPIResponse
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public ConstellationStatusAPIResponse fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,ConstellationStatusAPIResponse.class);
	}

}
