
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* ContentMeasurement
*/
public class ContentMeasurement {
	//Unix timestamp in seconds
	@JsonProperty("MeasureStarted")
	public long MeasureStarted;

	//Unix timestamp in seconds
	@JsonProperty("MeasureCompleted")
	public long MeasureCompleted;

	@JsonProperty("Components")
	public ArrayList<ContentMeasurementComponent> Components;


	public ContentMeasurement(){ }

	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	static public ContentMeasurement fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,ContentMeasurement.class);
	}

}
