
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* CustomRemoteBucketSettings
*/
public class CustomRemoteBucketSettings {
	@JsonProperty("URL")
	public String URL = "";


	public CustomRemoteBucketSettings(){ }

	/**
	* @return JSON representation of the CustomRemoteBucketSettings
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a CustomRemoteBucketSettings
	* @return The deserialized CustomRemoteBucketSettings
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public CustomRemoteBucketSettings fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,CustomRemoteBucketSettings.class);
	}

}
