
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* DefaultEmailReportPolicy
*/
public class DefaultEmailReportPolicy {
	//If true, the email reports will use the custom configuration that is defined in UserCustomEmailSettings / Reports
	//fields.
	//If false, the email reports will use configuration from the policy setting if present, or else from the built-in
	//system default email report configuration.
	@JsonProperty("ShouldOverrideDefaultReports")
	public boolean ShouldOverrideDefaultReports;

	@JsonProperty("Reports")
	public ArrayList<EmailReportConfig> Reports;


	public DefaultEmailReportPolicy(){ }

	/**
	* @return JSON representation of the DefaultEmailReportPolicy
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a DefaultEmailReportPolicy
	* @return The deserialized DefaultEmailReportPolicy
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public DefaultEmailReportPolicy fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,DefaultEmailReportPolicy.class);
	}

	/**
	* @return Returns a copy of the embedded UserCustomEmailSettings
	*/
	public UserCustomEmailSettings GetEmbeddedUserCustomEmailSettings(){
		var ret = new UserCustomEmailSettings();
		ret.Reports = this.Reports;
		return ret;
	}
	public void SetEmbeddedUserCustomEmailSettings(UserCustomEmailSettings other){
		this.Reports = other.Reports;
	}

}
