
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* DefaultSourceWithOSRestriction
*/
public class DefaultSourceWithOSRestriction {
	@JsonProperty("SourceConfig")
	public SourceConfig SourceConfig;

	@JsonProperty("RestrictOS")
	public int RestrictOS;


	public DefaultSourceWithOSRestriction(){ }

	/**
	* @return JSON representation of the DefaultSourceWithOSRestriction
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a DefaultSourceWithOSRestriction
	* @return The deserialized DefaultSourceWithOSRestriction
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public DefaultSourceWithOSRestriction fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,DefaultSourceWithOSRestriction.class);
	}

}
