
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* DestinationStatistics
*/
public class DestinationStatistics {
	@JsonProperty("ClientProvidedSize")
	public SizeMeasurement ClientProvidedSize;

	@JsonProperty("ClientProvidedContent")
	public ContentMeasurement ClientProvidedContent;

	@JsonProperty("LastSuccessfulDeepVerify_GUID")
	public String LastSuccessfulDeepVerify_GUID = "";

	//Unix timestamp in seconds
	@JsonProperty("LastSuccessfulDeepVerify_StartTime")
	public long LastSuccessfulDeepVerify_StartTime;

	//Unix timestamp in seconds
	@JsonProperty("LastSuccessfulDeepVerify_EndTime")
	public long LastSuccessfulDeepVerify_EndTime;


	public DestinationStatistics(){ }

	/**
	* @return JSON representation of the DestinationStatistics
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a DestinationStatistics
	* @return The deserialized DestinationStatistics
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public DestinationStatistics fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,DestinationStatistics.class);
	}

}
