
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* DispatcherListSnapshotVirtualMachinesResponse
* @since Version : 24.12.x
*/
public class DispatcherListSnapshotVirtualMachinesResponse {
	//If the operation was successful, the status will be in the 200-299 range.
	@JsonProperty("Status")
	public int Status;

	@JsonProperty("Message")
	public String Message = "";

	@JsonProperty("VMs")
	public ArrayList<VMInfo> VMs;


	public DispatcherListSnapshotVirtualMachinesResponse(){ }

	/**
	* @return JSON representation of the DispatcherListSnapshotVirtualMachinesResponse
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a DispatcherListSnapshotVirtualMachinesResponse
	* @return The deserialized DispatcherListSnapshotVirtualMachinesResponse
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public DispatcherListSnapshotVirtualMachinesResponse fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,DispatcherListSnapshotVirtualMachinesResponse.class);
	}

	/**
	* @return Returns a copy of the embedded CometAPIResponseMessage
	*/
	public CometAPIResponseMessage GetEmbeddedCometAPIResponseMessage(){
		var ret = new CometAPIResponseMessage();
		ret.Status = this.Status;
		ret.Message = this.Message;
		return ret;
	}
	public void SetEmbeddedCometAPIResponseMessage(CometAPIResponseMessage other){
		this.Status = other.Status;
		this.Message = other.Message;
	}

	/**
	* @return Returns a copy of the embedded VMInfoList
	*/
	public VMInfoList GetEmbeddedVMInfoList(){
		var ret = new VMInfoList();
		ret.VMs = this.VMs;
		return ret;
	}
	public void SetEmbeddedVMInfoList(VMInfoList other){
		this.VMs = other.VMs;
	}

}
