
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* ExternalAuthenticationSourceDisplay
*/
public class ExternalAuthenticationSourceDisplay {
	@JsonProperty("DisplayName")
	public String DisplayName = "";

	@JsonProperty("LoginStartURL")
	public String LoginStartURL = "";


	public ExternalAuthenticationSourceDisplay(){ }

	/**
	* @return JSON representation of the ExternalAuthenticationSourceDisplay
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a ExternalAuthenticationSourceDisplay
	* @return The deserialized ExternalAuthenticationSourceDisplay
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public ExternalAuthenticationSourceDisplay fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,ExternalAuthenticationSourceDisplay.class);
	}

}
