
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* GetProfileAndHashResponseMessage
*/
public class GetProfileAndHashResponseMessage {
	//If the operation was successful, the status will be in the 200-299 range.
	@JsonProperty("Status")
	public int Status;

	@JsonProperty("Message")
	public String Message = "";

	//A hash identifier for the current state of the user's profile. If you supply this in the AdminSetUserProfileHash API,
	//the server can safely reject your change if another change has happened concurrently. This allows you to retry the
	//request.
	@JsonProperty("ProfileHash")
	public String ProfileHash = "";

	@JsonProperty("Profile")
	public UserProfileConfig Profile;


	public GetProfileAndHashResponseMessage(){ }

	/**
	* @return JSON representation of the GetProfileAndHashResponseMessage
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a GetProfileAndHashResponseMessage
	* @return The deserialized GetProfileAndHashResponseMessage
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public GetProfileAndHashResponseMessage fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,GetProfileAndHashResponseMessage.class);
	}

	/**
	* @return Returns a copy of the embedded CometAPIResponseMessage
	*/
	public CometAPIResponseMessage GetEmbeddedCometAPIResponseMessage(){
		var ret = new CometAPIResponseMessage();
		ret.Status = this.Status;
		ret.Message = this.Message;
		return ret;
	}
	public void SetEmbeddedCometAPIResponseMessage(CometAPIResponseMessage other){
		this.Status = other.Status;
		this.Message = other.Message;
	}

}
