
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* GlobalOverrideOptions
*/
public class GlobalOverrideOptions {
	@JsonProperty("RandomDelaySecs")
	public long RandomDelaySecs;


	public GlobalOverrideOptions(){ }

	/**
	* @return JSON representation of the GlobalOverrideOptions
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a GlobalOverrideOptions
	* @return The deserialized GlobalOverrideOptions
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public GlobalOverrideOptions fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,GlobalOverrideOptions.class);
	}

}
