
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* HyperVRestoreTargetOptions
*/
public class HyperVRestoreTargetOptions {
	@JsonProperty("DiskStoragePath")
	public String DiskStoragePath = "";


	public HyperVRestoreTargetOptions(){ }

	/**
	* @return JSON representation of the HyperVRestoreTargetOptions
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a HyperVRestoreTargetOptions
	* @return The deserialized HyperVRestoreTargetOptions
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public HyperVRestoreTargetOptions fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,HyperVRestoreTargetOptions.class);
	}

}
