
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* HyperVMachineInfo
*/
public class HyperVMachineInfo {
	@JsonProperty("ID")
	public String ID = "";

	@JsonProperty("Name")
	public String DisplayName = "";


	public HyperVMachineInfo(){ }

	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	static public HyperVMachineInfo fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,HyperVMachineInfo.class);
	}

}
