
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* ImpossibleCloudPartnerTemplateSettings
* @since Version : 24.3.1
*/
public class ImpossibleCloudPartnerTemplateSettings {
	//Optional. The region for your Partner console and for provisioning new buckets. If blank, uses the default region for
	//Impossible Cloud (eu-central-2).
	@JsonProperty("Region")
	public String Region = "";

	@JsonProperty("AccessKey")
	public String AccessKey = "";


	public ImpossibleCloudPartnerTemplateSettings(){ }

	/**
	* @return JSON representation of the ImpossibleCloudPartnerTemplateSettings
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a ImpossibleCloudPartnerTemplateSettings
	* @return The deserialized ImpossibleCloudPartnerTemplateSettings
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public ImpossibleCloudPartnerTemplateSettings fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,ImpossibleCloudPartnerTemplateSettings.class);
	}

}
