
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* JobEntry JobEntry is a single entry within a job report.
*/
public class JobEntry {
	//Unix timestamp in seconds
	@JsonProperty("Time")
	public long Time;

	//One of the SEVERITY_ constants.
	@JsonProperty("Severity")
	public String Severity = "";

	@JsonProperty("Message")
	public String Message = "";


	public JobEntry(){ }

	/**
	* @return JSON representation of the JobEntry
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a JobEntry
	* @return The deserialized JobEntry
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public JobEntry fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,JobEntry.class);
	}

}
