
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* LicenseLimits
*/
public class LicenseLimits {
	@JsonProperty("deviceCount")
	public int DeviceCount;

	@JsonProperty("boosterCount")
	public HashMap<String, Integer> BoosterCount;


	public LicenseLimits(){ }

	/**
	* @return JSON representation of the LicenseLimits
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a LicenseLimits
	* @return The deserialized LicenseLimits
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public LicenseLimits fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,LicenseLimits.class);
	}

}
