
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* LocalDestinationLocation
*/
public class LocalDestinationLocation {
	@JsonProperty("LocalcopyPath")
	public String LocalcopyPath = "";

	//If logging in to a Windows network share (SMB/CIFS) is required, enter the username here.
	@JsonProperty("LocalcopyWinSMBUsername")
	public String LocalcopyWinSMBUsername = "";

	//If logging in to a Windows network share (SMB/CIFS) is required, enter the password here. The password may be hashed
	//as per the LocalcopyWinSMBPasswordFormat field.
	@JsonProperty("LocalcopyWinSMBPassword")
	public String LocalcopyWinSMBPassword = "";

	//One of the PASSWORD_FORMAT_ constants. It controls the hash format of the LocalcopyWinSMBPassword field.
	@JsonProperty("LocalcopyWinSMBPasswordFormat")
	public long LocalcopyWinSMBPasswordFormat;


	public LocalDestinationLocation(){ }

	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	static public LocalDestinationLocation fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,LocalDestinationLocation.class);
	}

}
