
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* LoginProtectionOptions
*/
public class LoginProtectionOptions {
	//Enable this feature to block repeated failed login attempts to the Comet Server.
	@JsonProperty("Enabled")
	public boolean Enabled;

	//The number of failed attempts before a cooldown is applied. If the feature is enabled, should be at least 1.
	@JsonProperty("FailureThreshold")
	public long FailureThreshold;

	//The duration to block requests, in seconds. If the feature is enabled, should be at least 1 second.
	@JsonProperty("CooldownSeconds")
	public long CooldownSeconds;


	public LoginProtectionOptions(){ }

	/**
	* @return JSON representation of the LoginProtectionOptions
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a LoginProtectionOptions
	* @return The deserialized LoginProtectionOptions
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public LoginProtectionOptions fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,LoginProtectionOptions.class);
	}

}
