
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* MSSQLConnection
*/
public class MSSQLConnection {
	//One of the MSSQL_AUTH_ constants (e.g. "windows" or "native")
	@JsonProperty("Type")
	public String Type = "";

	@JsonProperty("Username")
	public String Username = "";

	@JsonProperty("Password")
	public String Password = "";


	// deprecated since Comet version Unused
	@JsonProperty("Hostname")
	public String Hostname = "";

	@JsonProperty("InstanceName")
	public String InstanceName = "";

	//One of the MSSQL_METHOD_ constants, to control using x86_32 or x86_64 OLEDB drivers
	@JsonProperty("Method")
	public String Method = "";


	public MSSQLConnection(){ }

	/**
	* @return JSON representation of the MSSQLConnection
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a MSSQLConnection
	* @return The deserialized MSSQLConnection
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public MSSQLConnection fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,MSSQLConnection.class);
	}

}
