
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* Office365CustomSettingV2 Office365CustomSettingV2 is used in the EngineProps for an Office 365 Protected Item (see
* ENGINE_BUILTIN_MSOFFICE).
* @since Version : 21.9.xx
*/
public class Office365CustomSettingV2 {

	// deprecated since Comet version 24.12.2
	//If true, then backup everything except the selected users (group members are still included)
	@JsonProperty("Organization")
	public boolean Organization;

	//If true, exclude all filtered IDs and Members. Backup everything else
	@JsonProperty("FilterMode")
	public boolean FilterMode;

	//Key is the ID of User, Group, or Site
	//Value is a bitset of the SERVICE_ constants, to select which services to back up for members
	@JsonProperty("BackupOptions")
	public HashMap<String, Long> BackupOptions;

	//Key is the ID of a Group or Team Site
	//Value is a bitset of the SERVICE_ constants, to select which services to back up for members
	@JsonProperty("MemberBackupOptions")
	public HashMap<String, Long> MemberBackupOptions;

	//Key is the ID of a User, Group, or Site
	//Value is a bitset of the SERVICE_ constants, to select which services to back up for members
	@JsonProperty("FilterOptions")
	public HashMap<String, Long> FilterOptions;

	//Key is the ID of a Group or Team Site
	//Value is a bitset of the SERVICE_ constants, to select which services to back up for members
	@JsonProperty("FilterMemberOptions")
	public HashMap<String, Long> FilterMemberOptions;


	public Office365CustomSettingV2(){ }

	/**
	* @return JSON representation of the Office365CustomSettingV2
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a Office365CustomSettingV2
	* @return The deserialized Office365CustomSettingV2
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public Office365CustomSettingV2 fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,Office365CustomSettingV2.class);
	}

}
