
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* Office365Connection
*/
public class Office365Connection {
	@JsonProperty("FeatureFlag")
	public String FeatureFlag = "";

	@JsonProperty("Credential")
	public Office365Credential Credential;

	@JsonProperty("CustomSetting")
	public Office365CustomSetting CustomSetting;

	@JsonProperty("MailboxUniqueMembers")
	public ArrayList<String> MailboxUniqueMembers;

	@JsonProperty("SiteUniqueMembers")
	public ArrayList<String> SiteUniqueMembers;

	@JsonProperty("CustomSettingV2")
	public Office365CustomSettingV2 CustomSettingV2;


	public Office365Connection(){ }

	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	static public Office365Connection fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,Office365Connection.class);
	}

}
