
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* Office365ObjectInfo
*/
public class Office365ObjectInfo {
	@JsonProperty("GUID")
	public String GUID = "";

	@JsonProperty("Name")
	public String Name = "";

	@JsonProperty("Type")
	public String Type = "";

	//May be an email address or a SharePoint site URL
	@JsonProperty("Value")
	public String Value = "";

	@JsonProperty("Members")
	public ArrayList<String> Members;


	public Office365ObjectInfo(){ }

	/**
	* @return JSON representation of the Office365ObjectInfo
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a Office365ObjectInfo
	* @return The deserialized Office365ObjectInfo
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public Office365ObjectInfo fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,Office365ObjectInfo.class);
	}

}
