
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* Office365CustomSetting Office365CustomSetting is used in the EngineProps for an Office 365 Protected Item (see
* ENGINE_BUILTIN_MSOFFICE).
* If present, it will be automatically converted to the replacement Office365CustomSettingV2 type.
// deprecated since Comet version 21.9.xx
*/
public class Office365CustomSetting {
	@JsonProperty("MailboxStrategy")
	public String MailboxStrategy = "";

	@JsonProperty("SiteStrategy")
	public String SiteStrategy = "";

	@JsonProperty("MailboxUserIDs")
	public ArrayList<String> MailboxUserIDs;

	@JsonProperty("MailboxGroupIDs")
	public ArrayList<String> MailboxGroupIDs;

	@JsonProperty("SiteIDs")
	public ArrayList<String> SiteIDs;


	public Office365CustomSetting(){ }

	/**
	* @return JSON representation of the Office365CustomSetting
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a Office365CustomSetting
	* @return The deserialized Office365CustomSetting
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public Office365CustomSetting fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,Office365CustomSetting.class);
	}

}
