
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* OrganizationLoginURLResponse
*/
public class OrganizationLoginURLResponse {
	@JsonProperty("LoginURL")
	public String LoginURL = "";


	public OrganizationLoginURLResponse(){ }

	/**
	* @return JSON representation of the OrganizationLoginURLResponse
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a OrganizationLoginURLResponse
	* @return The deserialized OrganizationLoginURLResponse
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public OrganizationLoginURLResponse fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,OrganizationLoginURLResponse.class);
	}

}
