
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* ProtectedItemEngineTypePolicy
*/
public class ProtectedItemEngineTypePolicy {
	@JsonProperty("ShouldRestrictEngineTypeList")
	public boolean ShouldRestrictEngineTypeList;

	@JsonProperty("AllowedEngineTypeWhenRestricted")
	public ArrayList<String> AllowedEngineTypeWhenRestricted;


	public ProtectedItemEngineTypePolicy(){ }

	/**
	* @return JSON representation of the ProtectedItemEngineTypePolicy
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a ProtectedItemEngineTypePolicy
	* @return The deserialized ProtectedItemEngineTypePolicy
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public ProtectedItemEngineTypePolicy fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,ProtectedItemEngineTypePolicy.class);
	}

}
