
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* ProtectedItemWithBackupRulesResponse
*/
public class ProtectedItemWithBackupRulesResponse {
	//If the operation was successful, the status will be in the 200-299 range.
	@JsonProperty("Status")
	public int Status;

	@JsonProperty("Message")
	public String Message = "";

	//The Protected Item configuration
	@JsonProperty("Source")
	public SourceConfig Source;

	//All backup rules for the Protected Item
	@JsonProperty("BackupRules")
	public HashMap<String, BackupRuleConfig> BackupRules;

	@JsonProperty("ProfileHash")
	public String ProfileHash = "";


	public ProtectedItemWithBackupRulesResponse(){ }

	/**
	* @return JSON representation of the ProtectedItemWithBackupRulesResponse
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a ProtectedItemWithBackupRulesResponse
	* @return The deserialized ProtectedItemWithBackupRulesResponse
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public ProtectedItemWithBackupRulesResponse fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,ProtectedItemWithBackupRulesResponse.class);
	}

	/**
	* @return Returns a copy of the embedded CometAPIResponseMessage
	*/
	public CometAPIResponseMessage GetEmbeddedCometAPIResponseMessage(){
		var ret = new CometAPIResponseMessage();
		ret.Status = this.Status;
		ret.Message = this.Message;
		return ret;
	}
	public void SetEmbeddedCometAPIResponseMessage(CometAPIResponseMessage other){
		this.Status = other.Status;
		this.Message = other.Message;
	}

}
