
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* ProxmoxConnection
*/
public class ProxmoxConnection {
	@JsonProperty("SSH")
	public SSHConnection SSH;


	public ProxmoxConnection(){ }

	/**
	* @return JSON representation of the ProxmoxConnection
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a ProxmoxConnection
	* @return The deserialized ProxmoxConnection
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public ProxmoxConnection fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,ProxmoxConnection.class);
	}

}
