
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* PSAConfig
*/
public class PSAConfig {
	//For PSA_TYPE_GRADIENT. Defaults to enabled
	@JsonProperty("AlertsDisabled")
	public boolean AlertsDisabled;

	@JsonProperty("CustomHeaders")
	public HashMap<String, String> CustomHeaders;

	//Specified credentials for the target PSA
	@JsonProperty("PartnerKey")
	public String PartnerKey = "";

	//One of the PSA_TYPE_ constants
	@JsonProperty("Type")
	public int Type;

	//For PSA_TYPE_GENERIC
	@JsonProperty("URL")
	public String URL = "";

	@JsonProperty("GroupedBy")
	public PSAGroupedBy GroupedBy;


	public PSAConfig(){ }

	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	static public PSAConfig fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,PSAConfig.class);
	}

}
