
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* PSAGroupedBy
*/
public class PSAGroupedBy {
	@JsonProperty("Users")
	public boolean Users;

	@JsonProperty("Tenants")
	public boolean Tenants;

	@JsonProperty("AccountName")
	public boolean AccountName;


	public PSAGroupedBy(){ }

	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	static public PSAGroupedBy fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,PSAGroupedBy.class);
	}

}
