
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* PVEBackupNode
*/
public class PVEBackupNode {
	@JsonProperty("IncludedVMs")
	public ArrayList<PVEBackupVM> IncludedVMs;

	@JsonProperty("Name")
	public String Name = "";

	@JsonProperty("Selected")
	public boolean Selected;


	public PVEBackupNode(){ }

	/**
	* @return JSON representation of the PVEBackupNode
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a PVEBackupNode
	* @return The deserialized PVEBackupNode
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public PVEBackupNode fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,PVEBackupNode.class);
	}

}
