
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* PVEBackupDisk This type is used in the EngineProps for an &#34;engine1/proxmox&#34; Protected Item. It represents the
* selection state for a single disk attached to a single Proxmox VM or LXC Container. It is expected to be
* user-configurable.
* @since Version : 25.8.0
*/
public class PVEBackupDisk {
	//For a disk "scsi0", this field should contain: "scsi"
	@JsonProperty("Device")
	public String Device = "";

	//For a disk "scsi0", this field should contain: 0
	@JsonProperty("DeviceNum")
	public int DeviceNum;


	public PVEBackupDisk(){ }

	/**
	* @return JSON representation of the PVEBackupDisk
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a PVEBackupDisk
	* @return The deserialized PVEBackupDisk
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public PVEBackupDisk fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,PVEBackupDisk.class);
	}

}
