
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* PVEBackupVM
*/
public class PVEBackupVM {
	@JsonProperty("IncludedDisks")
	public ArrayList<PVEBackupDisk> IncludedDisks;

	@JsonProperty("Name")
	public String Name = "";

	@JsonProperty("Selected")
	public boolean Selected;

	@JsonProperty("Type")
	public String Type = "";

	@JsonProperty("VMID")
	public String VMID = "";


	public PVEBackupVM(){ }

	/**
	* @return JSON representation of the PVEBackupVM
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a PVEBackupVM
	* @return The deserialized PVEBackupVM
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public PVEBackupVM fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,PVEBackupVM.class);
	}

}
