
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* PVEBackupDisk
*/
public class PVEBackupDisk {
	@JsonProperty("Device")
	public String Device = "";

	@JsonProperty("DeviceNum")
	public int DeviceNum;


	public PVEBackupDisk(){ }

	/**
	* @return JSON representation of the PVEBackupDisk
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a PVEBackupDisk
	* @return The deserialized PVEBackupDisk
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public PVEBackupDisk fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,PVEBackupDisk.class);
	}

}
