
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* PVEDisk
*/
public class PVEDisk {
	@JsonProperty("Device")
	public String Device = "";

	@JsonProperty("DeviceNum")
	public int DeviceNum;

	@JsonProperty("StorageID")
	public String StorageID = "";

	@JsonProperty("Volume")
	public String Volume = "";

	@JsonProperty("Size")
	public String Size = "";

	@JsonProperty("Format")
	public String Format = "";

	@JsonProperty("Options")
	public String Options = "";


	public PVEDisk(){ }

	/**
	* @return JSON representation of the PVEDisk
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a PVEDisk
	* @return The deserialized PVEDisk
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public PVEDisk fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,PVEDisk.class);
	}

}
