
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* PVEParams
*/
public class PVEParams {
	@JsonProperty("Everything")
	public boolean Everything;

	@JsonProperty("Exclusions")
	public ArrayList<PVEBackupNode> Exclusions;

	@JsonProperty("Method")
	public String Method = "";

	@JsonProperty("Quota")
	public long Quota;

	@JsonProperty("SSHConnection")
	public SSHConnection SSHConnection;

	@JsonProperty("Selections")
	public ArrayList<PVEBackupNode> Selections;


	public PVEParams(){ }

	/**
	* @return JSON representation of the PVEParams
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a PVEParams
	* @return The deserialized PVEParams
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public PVEParams fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,PVEParams.class);
	}

}
