
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* PVEStorageName PVEStorageName contains the name and type of storage configured on a Proxmox Cluster
*/
public class PVEStorageName {
	@JsonProperty("Name")
	public String Name = "";

	@JsonProperty("Type")
	public String Type = "";

	@JsonProperty("Content")
	public ArrayList<String> Content;


	public PVEStorageName(){ }

	/**
	* @return JSON representation of the PVEStorageName
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a PVEStorageName
	* @return The deserialized PVEStorageName
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public PVEStorageName fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,PVEStorageName.class);
	}

}
