
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* PVEVM PVEVM describes a single Proxmox virtual machine or container.
*/
public class PVEVM {
	@JsonProperty("CPU")
	public String CPU = "";

	@JsonProperty("Disks")
	public ArrayList<PVEDisk> Disks;

	@JsonProperty("Memory")
	public String Memory = "";

	@JsonProperty("Name")
	public String Name = "";

	@JsonProperty("Node")
	public String Node = "";

	@JsonProperty("OSType")
	public String OSType = "";

	@JsonProperty("Running")
	public boolean Running;

	@JsonProperty("Type")
	public String Type = "";

	//String type, but always contains an integer value
	@JsonProperty("VMID")
	public String VMID = "";


	public PVEVM(){ }

	/**
	* @return JSON representation of the PVEVM
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a PVEVM
	* @return The deserialized PVEVM
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public PVEVM fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,PVEVM.class);
	}

}
