
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* RemoteServerAddress
*/
public class RemoteServerAddress {
	@JsonProperty("Type")
	public String Type = "";

	@JsonProperty("Description")
	public String Description = "";

	@JsonProperty("RemoteAddress")
	public String RemoteAddress = "";

	@JsonProperty("Username")
	public String Username = "";

	@JsonProperty("Password")
	public String Password = "";

	@JsonProperty("LDAP")
	public ExternalLDAPAuthenticationSourceSettings LDAP;

	@JsonProperty("OIDC")
	public OidcConfig OIDC;

	@JsonProperty("B2")
	public B2VirtualStorageRoleSettings B2;

	@JsonProperty("Wasabi")
	public WasabiVirtualStorageRoleSettings Wasabi;

	@JsonProperty("Custom")
	public CustomRemoteBucketSettings Custom;

	@JsonProperty("S3")
	public S3GenericVirtualStorageRole S3;

	//Amazon AWS - Virtual Storage Role
	@JsonProperty("AWS")
	public AmazonAWSVirtualStorageRoleSettings AWS;

	@JsonProperty("Storj")
	public StorjVirtualStorageRoleSetting Storj;


	public RemoteServerAddress(){ }

	/**
	* @return JSON representation of the RemoteServerAddress
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a RemoteServerAddress
	* @return The deserialized RemoteServerAddress
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public RemoteServerAddress fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,RemoteServerAddress.class);
	}

}
