
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* RemoteServerAddress
*/
public class RemoteServerAddress {
	@JsonProperty("Type")
	public String Type = "";

	@JsonProperty("Description")
	public String Description = "";

	//For use with Comet Server (Storage Role / Auth Role)
	@JsonProperty("RemoteAddress")
	public String RemoteAddress = "";

	//For use with Comet Server (Storage Role / Auth Role)
	@JsonProperty("Username")
	public String Username = "";

	//For use with Comet Server (Storage Role / Auth Role)
	@JsonProperty("Password")
	public String Password = "";

	@JsonProperty("LDAP")
	public ExternalLDAPAuthenticationSourceSettings LDAP;

	@JsonProperty("OIDC")
	public OidcConfig OIDC;

	//Backblaze B2 (Storage Template / Constellation)
	@JsonProperty("B2")
	public B2VirtualStorageRoleSettings B2;

	//Wasabi, or Comet Storage powered by Wasabi (Storage Template / Constellation)
	@JsonProperty("Wasabi")
	public WasabiVirtualStorageRoleSettings Wasabi;

	//Custom Remote Bucket HTTP protocol (Storage Template)
	@JsonProperty("Custom")
	public CustomRemoteBucketSettings Custom;

	//IDrive e2, or Custom IAM-compatible (Storage Template / Constellation)
	@JsonProperty("S3")
	public S3GenericVirtualStorageRole S3;

	//Amazon AWS (Storage Template / Constellation)
	@JsonProperty("AWS")
	public AmazonAWSVirtualStorageRoleSettings AWS;

	//Storj (Storage Template / Constellation)
	@JsonProperty("Storj")
	public StorjVirtualStorageRoleSetting Storj;

	//Impossible Cloud Partner API (Storage Template / Constellation)
	@JsonProperty("ImpPartner")
	public ImpossibleCloudPartnerTemplateSettings ImpPartner;

	//Impossible Cloud IAM API (Storage Template / Constellation)
	@JsonProperty("ImpUser")
	public ImpossibleCloudIAMTemplateSettings ImpUser;


	public RemoteServerAddress(){ }

	/**
	* @return JSON representation of the RemoteServerAddress
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a RemoteServerAddress
	* @return The deserialized RemoteServerAddress
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public RemoteServerAddress fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,RemoteServerAddress.class);
	}

}
