
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* ReplicatorStateAPIResponse
*/
public class ReplicatorStateAPIResponse {
	@JsonProperty("Description")
	public String Description = "";

	@JsonProperty("RemoteServerID")
	public String RemoteServerID = "";

	@JsonProperty("DisplayClass")
	public int DisplayClass;

	@JsonProperty("ActiveWorkers")
	public int ActiveWorkers;

	@JsonProperty("TotalWorkers")
	public int TotalWorkers;

	@JsonProperty("State")
	public int State;

	@JsonProperty("ItemsQueued")
	public int ItemsQueued;

	@JsonProperty("BytesQueued")
	public long BytesQueued;

	@JsonProperty("LastWorkerSubmitTime")
	public long LastWorkerSubmitTime;

	@JsonProperty("CurrentTime")
	public long CurrentTime;

	@JsonProperty("ItemsReplicated")
	public long ItemsReplicated;

	@JsonProperty("BytesReplicated")
	public long BytesReplicated;


	public ReplicatorStateAPIResponse(){ }

	/**
	* @return JSON representation of the ReplicatorStateAPIResponse
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a ReplicatorStateAPIResponse
	* @return The deserialized ReplicatorStateAPIResponse
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public ReplicatorStateAPIResponse fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,ReplicatorStateAPIResponse.class);
	}

}
