
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* RestoreJobAdvancedOptions
*/
public class RestoreJobAdvancedOptions {
	//One of the RESTORETYPE_ constants
	@JsonProperty("Type")
	public int Type;

	//For RESTORETYPE_FILE
	@JsonProperty("OverwriteExistingFiles")
	public boolean OverwriteExistingFiles;

	//For RESTORETYPE_FILE. If set, OverwriteExistingFiles must be true
	@JsonProperty("OverwriteIfNewer")
	public boolean OverwriteIfNewer;

	//For RESTORETYPE_FILE. If set, OverwriteExistingFiles must be true
	@JsonProperty("OverwriteIfDifferentContent")
	public boolean OverwriteIfDifferentContent;

	//For RESTORETYPE_FILE. If set, OverwriteExistingFiles must be true. This can be set in combination with other
	//OverwriteIf options.
	@JsonProperty("OverwriteForcePermissions")
	public boolean OverwriteForcePermissions;

	//For RESTORETYPE_FILE. If set, DestPath must be blank
	@JsonProperty("DestIsOriginalLocation")
	public boolean DestIsOriginalLocation;

	//For RESTORETYPE_FILE or RESTORETYPE_PROCESS_xxx
	@JsonProperty("DestPath")
	public String DestPath = "";

	//For RESTORETYPE_WINDISK only. Must have one entry for each selected restore path
	@JsonProperty("ExactDestPaths")
	public ArrayList<String> ExactDestPaths;

	//For RESTORETYPE_FILE_ARCHIVE or RESTORETYPE_PROCESS_ARCHIVE. Default 0 is *.tar, for backward compatibility
	@JsonProperty("ArchiveFormat")
	public int ArchiveFormat;

	//Default disabled. For RESTORETYPE_FILE and RESTORETYPE_WINDISK. Used to continue the restore job when unreadable data
	//chunks are found.
	//Corresponds to the "Allow partial file restores (zero-out unrecoverable data)" option
	@JsonProperty("SkipUnreadableChunks")
	public boolean SkipUnreadableChunks;

	//Default disabled. Used to store the index files on disk instead of in memory.
	//Corresponds to the "Prefer temporary files instead of RAM (slower)" option
	@JsonProperty("OnDiskIndexesKey")
	public boolean OnDiskIndexesKey;

	//For RESTORETYPE_OFFICE365_CLOUD.
	@JsonProperty("Office365Credential")
	public Office365Credential Office365Credential;

	//For RESTORETYPE_MYSQL
	@JsonProperty("Username")
	public String Username = "";

	//For RESTORETYPE_MYSQL
	@JsonProperty("Password")
	public String Password = "";

	//For RESTORETYPE_MYSQL
	@JsonProperty("Host")
	public String Host = "";

	//For RESTORETYPE_MYSQL
	@JsonProperty("Port")
	public String Port = "";

	//For RESTORETYPE_MYSQL
	@JsonProperty("UseSsl")
	public boolean UseSsl;

	//For RESTORETYPE_MYSQL i.e.: Self signed certs
	@JsonProperty("SslAllowInvalid")
	public boolean SslAllowInvalid;

	//For RESTORETYPE_MYSQL
	@JsonProperty("SslCaFile")
	public String SslCaFile = "";

	//For RESTORETYPE_MYSQL
	@JsonProperty("SslCrtFile")
	public String SslCrtFile = "";

	//For RESTORETYPE_MYSQL
	@JsonProperty("SslKeyFile")
	public String SslKeyFile = "";

	//For RESTORETYPE_MSSQL.
	@JsonProperty("MsSqlConnection")
	public MSSQLLoginArgs MsSqlConnection;


	public RestoreJobAdvancedOptions(){ }

	/**
	* @return JSON representation of the RestoreJobAdvancedOptions
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a RestoreJobAdvancedOptions
	* @return The deserialized RestoreJobAdvancedOptions
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public RestoreJobAdvancedOptions fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,RestoreJobAdvancedOptions.class);
	}

}
