
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* ServerConfigOptionsSoftwareBuildRoleFragment
*/
public class ServerConfigOptionsSoftwareBuildRoleFragment {
	@JsonProperty("SoftwareBuildRole")
	public SoftwareBuildRoleOptions SoftwareBuildRole;


	public ServerConfigOptionsSoftwareBuildRoleFragment(){ }

	/**
	* @return JSON representation of the ServerConfigOptionsSoftwareBuildRoleFragment
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a ServerConfigOptionsSoftwareBuildRoleFragment
	* @return The deserialized ServerConfigOptionsSoftwareBuildRoleFragment
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public ServerConfigOptionsSoftwareBuildRoleFragment fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,ServerConfigOptionsSoftwareBuildRoleFragment.class);
	}

}
