
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* SessionOptions
*/
public class SessionOptions {
	//The number of seconds, after which an administrator should be automatically logged out of the Comet Server web
	//interface. If zero, will be replaced with DEFAULT_SESSIONTIMEOUT.
	@JsonProperty("ExpiredInSeconds")
	public long ExpiredInSeconds;


	public SessionOptions(){ }

	/**
	* @return JSON representation of the SessionOptions
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a SessionOptions
	* @return The deserialized SessionOptions
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public SessionOptions fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,SessionOptions.class);
	}

}
