
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* SharedStorageQuota A SharedStorageQuota can be applied to multiple Storage Vaults in the
* &#39;DestinationConfig.StorageLimitID&#39; field.
*/
public class SharedStorageQuota {
	@JsonProperty("Description")
	public String Description = "";

	@JsonProperty("OrganizationID")
	public String OrganizationID = "";

	//Bytes
	@JsonProperty("LimitBytes")
	public long LimitBytes;


	public SharedStorageQuota(){ }

	/**
	* @return JSON representation of the SharedStorageQuota
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a SharedStorageQuota
	* @return The deserialized SharedStorageQuota
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public SharedStorageQuota fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,SharedStorageQuota.class);
	}

}
