
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* SingleFieldSource
*/
public class SingleFieldSource {
	@JsonProperty("FieldName")
	public String FieldName = "";

	//One of "bool" / "int" / "string"
	@JsonProperty("FieldType")
	public String FieldType = "";

	@JsonProperty("BoolVal")
	public boolean BoolVal;

	@JsonProperty("IntVal")
	public long IntVal;

	@JsonProperty("StrVal")
	public String StrVal = "";


	public SingleFieldSource(){ }

	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	static public SingleFieldSource fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,SingleFieldSource.class);
	}

}
