
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* SizeMeasurement
*/
public class SizeMeasurement {
	//Bytes
	@JsonProperty("Size")
	public long Size;

	//Unix timestamp in seconds
	@JsonProperty("MeasureStarted")
	public long MeasureStarted;

	//Unix timestamp in seconds
	@JsonProperty("MeasureCompleted")
	public long MeasureCompleted;


	public SizeMeasurement(){ }

	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	static public SizeMeasurement fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,SizeMeasurement.class);
	}

}
