
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* SoftwareUpdateNewsResponse
*/
public class SoftwareUpdateNewsResponse {
	//The latest "Quarterly" release version of Comet known to the account.cometbackup.com system.
	@JsonProperty("latest_stable")
	public String LatestStable = "";

	//The latest "Voyager" release version of Comet known to the account.cometbackup.com system.
	@JsonProperty("latest_prerelease")
	public String LatestPrerelease = "";

	//A URL linking to the Comet Server downloads page.
	@JsonProperty("downloads_url")
	public String DownloadsURL = "";

	//An array of recent news items written by Comet Backup staff. Entries are english plaintext.
	@JsonProperty("updates_info")
	public ArrayList<String> WhatsNew;


	public SoftwareUpdateNewsResponse(){ }

	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	static public SoftwareUpdateNewsResponse fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,SoftwareUpdateNewsResponse.class);
	}

}
