
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* SourceStatistics
*/
public class SourceStatistics {
	@JsonProperty("LastBackupJob")
	public BackupJobDetail LastBackupJob;

	@JsonProperty("LastSuccessfulBackupJob")
	public BackupJobDetail LastSuccessfulBackupJob;


	public SourceStatistics(){ }

	/**
	* @return JSON representation of the SourceStatistics
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a SourceStatistics
	* @return The deserialized SourceStatistics
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public SourceStatistics fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,SourceStatistics.class);
	}

}
