
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* StorageRoleOptions
*/
public class StorageRoleOptions {
	@JsonProperty("RoleEnabled")
	public boolean RoleEnabled;

	@JsonProperty("Storage")
	public DestinationLocation Storage;


	// deprecated since Comet version 17.3.5
	@JsonProperty("LocalStorage")
	public ArrayList<LocalStorageDirectory> LocalStorage_Legacy;

	@JsonProperty("ReplicateTo")
	public ArrayList<ReplicaServer> ReplicateTo;


	public StorageRoleOptions(){ }

	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	static public StorageRoleOptions fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,StorageRoleOptions.class);
	}

}
