
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* UpdateCampaignOptions This data structure describes which devices should receive a remote software upgrade. Both the
* target version criteria (UpgradeOlder/ReinstallCurrentVer/DowngradeNewer) and the target device criteria
* (ApplyDeviceFilter/DeviceFilter) must be met in order for the remote upgrade to be applied.
*/
public class UpdateCampaignOptions {
	@JsonProperty("Active")
	public boolean Active;

	@JsonProperty("UpgradeOlder")
	public boolean UpgradeOlder;

	@JsonProperty("ReinstallCurrentVer")
	public boolean ReinstallCurrentVer;

	@JsonProperty("DowngradeNewer")
	public boolean DowngradeNewer;

	//Choose whether this bulk upgrade campaign is allowed to interrupt a running backup job.
	@JsonProperty("ForceUpgradeRunning")
	public boolean ForceUpgradeRunning;

	//If true, then the UserFilter will be used to restrict which accounts and devices will be eligible for the software
	//update. If false, all users and devices will be eligible for the software update.
	@JsonProperty("ApplyDeviceFilter")
	public boolean ApplyDeviceFilter;

	@JsonProperty("DeviceFilter")
	public SearchClause DeviceFilter;


	public UpdateCampaignOptions(){ }

	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	static public UpdateCampaignOptions fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,UpdateCampaignOptions.class);
	}

}
