
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* UserCustomEmailSettings
*/
public class UserCustomEmailSettings {
	@JsonProperty("Reports")
	public ArrayList<EmailReportConfig> Reports;


	public UserCustomEmailSettings(){ }

	/**
	* @return JSON representation of the UserCustomEmailSettings
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a UserCustomEmailSettings
	* @return The deserialized UserCustomEmailSettings
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public UserCustomEmailSettings fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,UserCustomEmailSettings.class);
	}

}
