
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* UserCustomEmailSettings
*/
public class UserCustomEmailSettings {
	@JsonProperty("Reports")
	public ArrayList<EmailReportConfig> Reports;


	public UserCustomEmailSettings(){ }

	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	static public UserCustomEmailSettings fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,UserCustomEmailSettings.class);
	}

}
