
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* UserGroup
*/
public class UserGroup {
	//Unix timestamp in seconds
	@JsonProperty("CreatedAt")
	public long CreatedAt;

	@JsonProperty("OrganizationID")
	public String OrganizationID = "";

	@JsonProperty("Name")
	public String Name = "";


	public UserGroup(){ }

	/**
	* @return JSON representation of the UserGroup
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a UserGroup
	* @return The deserialized UserGroup
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public UserGroup fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,UserGroup.class);
	}

}
