
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* UserPolicy
*/
public class UserPolicy {
	@JsonProperty("PreventRequestStorageVault")
	public boolean PreventRequestStorageVault;

	@JsonProperty("PreventAddCustomStorageVault")
	public boolean PreventAddCustomStorageVault;

	@JsonProperty("PreventEditStorageVault")
	public boolean PreventEditStorageVault;

	@JsonProperty("HideCloudStorageBranding")
	public boolean HideCloudStorageBranding;

	@JsonProperty("PreventDeleteStorageVault")
	public boolean PreventDeleteStorageVault;

	@JsonProperty("StorageVaultProviders")
	public StorageVaultProviderPolicy StorageVaultProviders;

	@JsonProperty("PreventNewProtectedItem")
	public boolean PreventNewProtectedItem;

	@JsonProperty("PreventEditProtectedItem")
	public boolean PreventEditProtectedItem;

	@JsonProperty("PreventDeleteProtectedItem")
	public boolean PreventDeleteProtectedItem;

	@JsonProperty("ProtectedItemEngineTypes")
	public ProtectedItemEngineTypePolicy ProtectedItemEngineTypes;

	@JsonProperty("FileAndFolderMandatoryExclusions")
	public ArrayList<ExtraFileExclusion> FileAndFolderMandatoryExclusions;

	@JsonProperty("ModeScheduleSkipAlreadyRunning")
	public int ModeScheduleSkipAlreadyRunning;

	@JsonProperty("ModeScheduleLastJobFailDoRetry")
	public int ModeScheduleLastJobFailDoRetry;

	@JsonProperty("ModeLastJobFailDoRetryTime")
	public long ModeLastJobFailDoRetryTime;

	@JsonProperty("ModeLastJobFailDoRetryCount")
	public long ModeLastJobFailDoRetryCount;

	@JsonProperty("ModeAdminResetPassword")
	public int ModeAdminResetPassword;

	@JsonProperty("ModeAdminViewFilenames")
	public int ModeAdminViewFilenames;

	@JsonProperty("ModeRequireUserResetPassword")
	public int ModeRequireUserResetPassword;

	@JsonProperty("PreventDeleteSingleSnapshots")
	public boolean PreventDeleteSingleSnapshots;

	@JsonProperty("PreventChangeAccountPassword")
	public boolean PreventChangeAccountPassword;

	@JsonProperty("PreventChangeEmailSettings")
	public boolean PreventChangeEmailSettings;

	@JsonProperty("PreventChangeAccountName")
	public boolean PreventChangeAccountName;

	@JsonProperty("PreventOpenAppUI")
	public boolean PreventOpenAppUI;

	@JsonProperty("RequirePasswordOpenAppUI")
	public boolean RequirePasswordOpenAppUI;

	@JsonProperty("HideAppImport")
	public boolean HideAppImport;

	@JsonProperty("HideAppVersion")
	public boolean HideAppVersion;

	@JsonProperty("PreventOpenWebUI")
	public boolean PreventOpenWebUI;

	@JsonProperty("PreventViewDeviceNames")
	public boolean PreventViewDeviceNames;

	@JsonProperty("DefaultEmailReports")
	public DefaultEmailReportPolicy DefaultEmailReports;

	@JsonProperty("DefaultStorageVaultRetention")
	public RetentionPolicy DefaultStorageVaultRetention;

	@JsonProperty("EnforceStorageVaultRetention")
	public boolean EnforceStorageVaultRetention;

	@JsonProperty("PreventProtectedItemRetention")
	public boolean PreventProtectedItemRetention;

	@JsonProperty("AllowEditObjectLockRetention")
	public boolean AllowEditObjectLockRetention;

	@JsonProperty("DefaultSources")
	public HashMap<String, SourceConfig> DefaultSources;

	@JsonProperty("DefaultSourcesBackupRules")
	public HashMap<String, BackupRuleConfig> DefaultSourcesBackupRules;

	@JsonProperty("DefaultSourcesWithOSRestriction")
	public HashMap<String, DefaultSourceWithOSRestriction> DefaultSourcesWithOSRestriction;

	@JsonProperty("DefaultBackupRules")
	public HashMap<String, BackupRuleConfig> DefaultBackupRules;

	@JsonProperty("RandomDelaySecs")
	public long RandomDelaySecs;


	public UserPolicy(){ }

	/**
	* @return JSON representation of the UserPolicy
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a UserPolicy
	* @return The deserialized UserPolicy
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public UserPolicy fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,UserPolicy.class);
	}

}
