
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* UserOnServer
*/
public class UserOnServer {
	//The server where this user was found. The 0-based indexes here correspond to the entries inside
	//ConstellationRoleOptions->Servers.
	@JsonProperty("ServerID")
	public int ServerID;

	@JsonProperty("Username")
	public String Username = "";


	public UserOnServer(){ }

	/**
	* @return JSON representation of the UserOnServer
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a UserOnServer
	* @return The deserialized UserOnServer
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public UserOnServer fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,UserOnServer.class);
	}

}
