
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* VaultSnapshot
*/
public class VaultSnapshot {
	@JsonProperty("Snapshot")
	public String Snapshot = "";

	@JsonProperty("Source")
	public String Source = "";

	@JsonProperty("CreateTime")
	public long CreateTime;

	@JsonProperty("HasOriginalPathInfo")
	public boolean HasOriginalPathInfo;


	public VaultSnapshot(){ }

	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	static public VaultSnapshot fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,VaultSnapshot.class);
	}

}
