
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* VMDiskInfo
* @since Version : 24.12.x
*/
public class VMDiskInfo {
	//Relative path within this backup job snapshot to root disk files
	@JsonProperty("Path")
	public String Path = "";

	//The virtual size of the virtual disk
	@JsonProperty("Size")
	public long Size;

	//Controller number where the disk is associated to
	@JsonProperty("Controller")
	public long Controller;

	//Device number within the controller
	@JsonProperty("DeviceNum")
	public long DeviceNum;


	public VMDiskInfo(){ }

	/**
	* @return JSON representation of the VMDiskInfo
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a VMDiskInfo
	* @return The deserialized VMDiskInfo
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public VMDiskInfo fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,VMDiskInfo.class);
	}

}
