
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* VMInfo
* @since Version : 24.12.x
*/
public class VMInfo {
	@JsonProperty("ID")
	public String ID = "";

	@JsonProperty("Name")
	public String Name = "";

	@JsonProperty("CPUCores")
	public int CPUCores;

	//Bytes
	@JsonProperty("RamBytes")
	public long RamBytes;

	//The BIOS mode of this machine e.g. "Legacy"|"UEFI"
	@JsonProperty("FirmwareType")
	public String FirmwareType = "";

	//Relative path to config file or directory, if supported by this Protected Item type
	@JsonProperty("ConfigPath")
	public String ConfigPath = "";

	@JsonProperty("Disks")
	public ArrayList<VMDiskInfo> Disks;


	public VMInfo(){ }

	/**
	* @return JSON representation of the VMInfo
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a VMInfo
	* @return The deserialized VMInfo
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public VMInfo fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,VMInfo.class);
	}

}
