
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* VMInfoList
* @since Version : 24.12.x
*/
public class VMInfoList {
	@JsonProperty("VMs")
	public ArrayList<VMInfo> VMs;


	public VMInfoList(){ }

	/**
	* @return JSON representation of the VMInfoList
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a VMInfoList
	* @return The deserialized VMInfoList
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public VMInfoList fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,VMInfoList.class);
	}

}
