
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* VMwareHostInfo VMwareHostInfo describes a single VMware host within a VMware datacenter.
*/
public class VMwareHostInfo {
	@JsonProperty("Name")
	public String Name = "";


	public VMwareHostInfo(){ }

	/**
	* @return JSON representation of the VMwareHostInfo
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a VMwareHostInfo
	* @return The deserialized VMwareHostInfo
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public VMwareHostInfo fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,VMwareHostInfo.class);
	}

}
