
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* VMwareNetworkInfo VMwareNetworkInfo describes a single VMware network within a VMware datacenter.
*/
public class VMwareNetworkInfo {
	@JsonProperty("Name")
	public String Name = "";


	public VMwareNetworkInfo(){ }

	/**
	* @return JSON representation of the VMwareNetworkInfo
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a VMwareNetworkInfo
	* @return The deserialized VMwareNetworkInfo
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public VMwareNetworkInfo fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,VMwareNetworkInfo.class);
	}

}
