
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* VMwareDatacenterInfo VMwareDatacenterInfo describes a single VMware datacenter.
*/
public class VMwareDatacenterInfo {
	@JsonProperty("Name")
	public String Name = "";


	public VMwareDatacenterInfo(){ }

	/**
	* @return JSON representation of the VMwareDatacenterInfo
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a VMwareDatacenterInfo
	* @return The deserialized VMwareDatacenterInfo
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public VMwareDatacenterInfo fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,VMwareDatacenterInfo.class);
	}

}
