
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* VMwareDatastoreInfo VMwareDatastoreInfo describes a single VMware datastore within a VMware datacenter.
*/
public class VMwareDatastoreInfo {
	@JsonProperty("Name")
	public String Name = "";


	public VMwareDatastoreInfo(){ }

	/**
	* @return JSON representation of the VMwareDatastoreInfo
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a VMwareDatastoreInfo
	* @return The deserialized VMwareDatastoreInfo
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public VMwareDatastoreInfo fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,VMwareDatastoreInfo.class);
	}

}
