
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* VMwareRestoreTargetOptions VMwareRestoreTargetOptions is used when restoring a virtual machine backup job into VMware,
* using the RESTORETYPE_VMHOST option.
* @since Version : 24.12.x
*/
public class VMwareRestoreTargetOptions {
	//The name of the VMware Datacenter to restore into. If blank and there is only one Datacenter in the vSphere
	//connection, it is chosen.
	@JsonProperty("Datacenter")
	public String Datacenter = "";

	//The name of the VMware Host within the VMware Datacenter to restore into. If blank and there is only one Datacenter
	//in the vSphere connection, it is chosen.
	@JsonProperty("Host")
	public String Host = "";

	//The name of the VMware Datastore on the VMware Host to restore into. If blank and there is only one Datacenter in the
	//vSphere connection, it is chosen.
	@JsonProperty("DatastorePath")
	public String DatastorePath = "";

	//The name of the VMware Network on the VMware Host to restore into. If blank and there is only one network on the
	//target vSphere connection, it is chosen.
	@JsonProperty("Network")
	public String Network = "";

	@JsonProperty("Connection")
	public VMwareConnection Connection;


	public VMwareRestoreTargetOptions(){ }

	/**
	* @return JSON representation of the VMwareRestoreTargetOptions
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a VMwareRestoreTargetOptions
	* @return The deserialized VMwareRestoreTargetOptions
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public VMwareRestoreTargetOptions fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,VMwareRestoreTargetOptions.class);
	}

}
