
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* VMwareMachineInfo
*/
public class VMwareMachineInfo {
	@JsonProperty("Name")
	public String Name = "";


	public VMwareMachineInfo(){ }

	/**
	* @return JSON representation of the VMwareMachineInfo
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a VMwareMachineInfo
	* @return The deserialized VMwareMachineInfo
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public VMwareMachineInfo fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,VMwareMachineInfo.class);
	}

}
