
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* VMwareConnection
*/
public class VMwareConnection {
	//One of the VMWARE_CONNECTION_ constants
	@JsonProperty("ConnectionType")
	public String ConnectionType = "";


	// deprecated since Comet version 23.9.11
	@JsonProperty("SSH")
	public SSHConnection SSH;

	@JsonProperty("VSphere")
	public VSphereConnection VSphere;


	public VMwareConnection(){ }

	/**
	* @return JSON representation of the VMwareConnection
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a VMwareConnection
	* @return The deserialized VMwareConnection
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public VMwareConnection fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,VMwareConnection.class);
	}

}
