
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* WebAuthnCredentialDescriptor
*/
public class WebAuthnCredentialDescriptor {
	@JsonProperty("type")
	public String Type = "";

	@JsonProperty("id")
	public byte[] CredentialID;

	@JsonProperty("transports")
	public ArrayList<String> Transport;


	public WebAuthnCredentialDescriptor(){ }

	/**
	* @return JSON representation of the WebAuthnCredentialDescriptor
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a WebAuthnCredentialDescriptor
	* @return The deserialized WebAuthnCredentialDescriptor
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public WebAuthnCredentialDescriptor fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,WebAuthnCredentialDescriptor.class);
	}

}
