
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* WebAuthnCredential
*/
public class WebAuthnCredential {
	@JsonProperty("PublicKey")
	public byte[] PublicKey;

	@JsonProperty("AttestationType")
	public String AttestationType = "";

	@JsonProperty("AAGUID")
	public byte[] AAGUID;

	@JsonProperty("SignCount")
	public long SignCount;

	@JsonProperty("CloneWarning")
	public boolean CloneWarning;


	public WebAuthnCredential(){ }

	/**
	* @return JSON representation of the WebAuthnCredential
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a WebAuthnCredential
	* @return The deserialized WebAuthnCredential
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public WebAuthnCredential fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,WebAuthnCredential.class);
	}

}
