
// AUTOGENERATED, DO NOT EDIT\n\n"
package com.cometbackup;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/**
* WebInterfaceBrandingProperties
*/
public class WebInterfaceBrandingProperties {
	//One of the BRANDINGSTYLETYPE_ constants
	@JsonProperty("BrandingStyleType")
	public int BrandingStyleType;

	@JsonProperty("BrandName")
	public String BrandName = "";

	@JsonProperty("LogoImage")
	public String LogoImage = "";

	@JsonProperty("TopColor")
	public String TopColor = "";

	@JsonProperty("AccentColor")
	public String AccentColor = "";

	@JsonProperty("Favicon")
	public String Favicon = "";

	@JsonProperty("HideNewsArea")
	public boolean HideNewsArea;


	public WebInterfaceBrandingProperties(){ }

	/**
	* @return JSON representation of the WebInterfaceBrandingProperties
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	public String toJson() throws JsonProcessingException {
		return CometAPI.getObjectMapper().writeValueAsString(this);
	}

	/**
	* @param jsStr JSON representation of a WebInterfaceBrandingProperties
	* @return The deserialized WebInterfaceBrandingProperties
	* @throws JsonProcessingException If JSON is malformed (should not happen)
	*/
	static public WebInterfaceBrandingProperties fromJson(String jsStr) throws JsonProcessingException {
		return CometAPI.getObjectMapper().readValue(jsStr,WebInterfaceBrandingProperties.class);
	}

}
